blog/urls.py
from django.views.generic import ListView, DetailView
from django.urls import path
from .models import Post
from blog.views import blog_home
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('',
        login_required(login_url='/login/')(
            ListView.as_view(
                queryset=Post.objects.all().order_by("-date")[:25],
                template_name="blog.html"
            )
        ),
        name='blog_home'
    ),
    path('<int:pk>/',
        login_required(login_url='/login/')(
            DetailView.as_view(
                model=Post,
                template_name="post.html"
            )
        ),
        name='blog_detail'
    ),
    path('blog/', blog_home, name='blog_home'),
    path('', ListView.as_view(), name='blog_home'),
    path('<int:pk>/', DetailView.as_view(), name='blog_detail'),
]

capstone/urls.py
from django.contrib import admin
from django.urls import path, include
from webapp import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('', include('webapp.urls')),
    path('blog/', include('blog.urls')),
    path('user_auth/', include('django.contrib.auth.urls')),
    path('user_auth/', include('user_auth.urls')),
    path('login/', include('login.urls'), name='login'),
    path('register/', include('register.urls')),
    path('logout/', auth_views.LogoutView.as_view(next_page='index'), name='logout'),


    
]

login/urls.py
from django.urls import path
from .views import login_view

app_name = 'login'

urlpatterns = [
    path('', login_view, name='login'),
]

register/urls.py
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [
     path('', views.register, name='register'),
]

user_auth/urls.py
from django.urls import path
from . import views

app_name = 'user_auth'

urlpatterns = [
     
     path('authenticate_user/', views.authenticate_user, name='authenticate_user'),
     path('show_user/', views.show_user, name='show_user'),
     
]

webapp/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'webapp'


urlpatterns = [
path('', views.index, name= 'index'),
path('about_me/',login_required(login_url='/login/')(views.about_me), name='about_me'),
path('contact/',views.contact, name='contact'),
path('dashboard/',login_required(login_url='/login/')(views.dashboard),name='dashboard')
]

blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
# Default behaviour - Django creates primary keys for you
    title = models.CharField(max_length=140)
    body = models.TextField()
    signature = models.CharField(max_length=140, default="The future belongs to those who believe in the beauty of their dreams.")
    date = models.DateTimeField()

    def __str__(self):
        return self.title
    

login/models.py
from django.db import models

# Create your models here.

register/models.py
from django.db import models

# Create your models here.

user_auth/models.py
from django.db import models

# Create your models here.

webapp/models.py
from django.db import models

# Create your models here.

login/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

register/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

blog/views.py
from django.shortcuts import render
from .models import Post
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='/login/')
def blog_home(request):
    posts = Post.objects.all()
    return render(request, 'blog.html', {'posts': posts})

login/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect 
from django.contrib.auth import authenticate, login

# Create your views here.

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('index') 
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})

register/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import UserRegisterForm


# Create your views here.

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created! You are now able to log in')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'register/register.html', {'form': form})

user_auth/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect


# Create your views here.

def user_login(request):
   return render(request, 'authentication/login.html')

def authenticate_user(request):
   username = request.POST['username']
   password = request.POST['password']
   user = authenticate(username=username, password=password)
   if user is None:
       return HttpResponseRedirect(
           reverse('user_auth:login')
       )
   else:
       login(request, user)
       return HttpResponseRedirect(
           reverse('user_auth:show_user')
       )

def show_user(request):
   print(request.user.username)
   return render(request, 'authentication/user.html', {
      "username": request.user.username,
      "password": request.user.password
   })

webapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request, "index.html")

@login_required(login_url='/login/')
def about_me(request):
    return render(request, "about_me.html")

def contact(request):
    return render(request, "webapp/contact.html")

@login_required(login_url='/login/')
def dashboard(request):
    return render(request, "dashboard.html")

blog/templates/blog.html
{% extends "header.html" %}

{% block content %}
    <h2>Blog Posts</h2>
    <ul>
    {% for post in object_list %}
        <li style="margin-bottom: 10px;"><a href="{% url 'blog_detail' post.id %}">{{ post.title }}</a></li>
    {% endfor %}
    </ul>
{% endblock %}

blog/templates/header.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Myra's Blog</title>

        <style>
          .heading {
        text-align: center;
            }
          </style>
    </head>
    <body>
        <h1>Welcome to Myra's Psych-IT Hub Blog</h1>
        <p style="line-height: 1.5; margin-bottom: 20px;">Here you will find posts about my experiences as an IT student and psychologist. I delve into captivating topics, 
           share insightful stories, and provide valuable information to engage and inspire the readers. From thought-provoking 
           articles to practical tips, this blog covers a wide range of subjects on psychology, technology, and personal growth. 
           Whether you're seeking inspiration, knowledge, or simply an enjoyable read, Myra's blog is your gateway to a world of 
           captivating content.</p>
        <main>
            {% block content %}
            {% endblock %}
        </main>

        <nav>
            <ul>
                <li style="margin-bottom: 10px;"><a href="{% url 'logout' %}">Logout</a></li> 
            </ul>
        </nav>
    </body>
    <footer>
        <p>&copy; 2023 Myra. All rights reserved.</p>
     </footer>
</html>

blog/templates/post.html
{% extends "header.html" %}

{% block content %}
<h3>{{ post.title }}</h3>
<h6>on {{ post.date }}</h6>
<div class="container">
    {{ post.body|safe|linebreaks}}
</div>
<br><br>
<a href="{% url 'blog_home' %}">Back to Blog Home</a>
{% endblock %}

blog/templates/protected_page.html
<!DOCTYPE html>
<html>
<head>
    <title>Protected Page</title>
</head>
<body>
    <h1>Welcome to the Protected Page</h1>
    <p>This is a page that requires login to access.</p>

    <h2>blog</h2>
    <p>This is the blog home page content.</p>
   
    <h2>post</h2>
    <p>This is the post page content.</p>
   
</body>
</html>

login/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    
    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer>
        <p>&copy; 2023 Myra. All rights reserved.</p>
    </footer>
</body>
</html>

login/templates/logged_out.html
<!DOCTYPE html>
<html>
<head>
    <title>Logged Out</title>
</head>
<body>
    <h2>You have been logged out</h2>
    <p>Thank you for using our website. You have been successfully logged out.</p>
</body>
</html>

login/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
    <p>Don't have an account? <a href="{% url 'register:register' %}">Register</a></p>
{% endblock %}

register/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}My Site{% endblock %}</title>
    {% block extra_head %}{% endblock %}
</head>
<body>
    <header>
    </header>
    <main>
        {% block content %}{% endblock %}
    </main>
    <footer>
        <p>&copy; 2023 Myra. All rights reserved.</p>
    </footer>
    {% block extra_body %}{% endblock %}
</body>
</html>

register/templates/register/register.html
{% extends 'base.html' %}

{% block content %}
  <h2>Register</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
  </form>
{% endblock %}

user_auth/templates/authentication/login.html
<h1> Login as User </h1>
<form action="{% url 'user_auth:authenticate_user' %}" method="post">
    {% csrf_token %}

    <label>Username</label>
    <input type="text" name="username" placeholder="User" required>
    <br/><br/>

    <label>Password</label>
    <input type="password" name="password" required>
    <br/><br/>
    <input type="submit" value="Login" />
</form>

user_auth/templates/authentication/user.html
<h1> Welcome, {{username}} </h1>
<p> Your password is {{password}}</p>

user_auth/templates/user_auth/authentication/login.html
<h1> Login as User </h1>
<form action="{% url 'user_auth:authenticate_user' %}" method="post">
    {% csrf_token %}

    <label>Username</label>
    <input type="text" name="username" placeholder="User" required>
    <br/><br/>

    <label>Password</label>
    <input type="password" name="password" required>
    <br/><br/>
    <input type="submit" value="Login" />
</form>

user_auth/templates/user_auth/authentication/user.html
<h1> Welcome, {{username}} </h1>
<p> Your password is {{password}}</p>

webapp/templates/about_me.html
<!DOCTYPE html>
<html>
<head> 
	<title>about_me</title>
	<style>
		.heading {
	text-align: center;
    	}
    </style>	
</head>

<header>
	<div class="heading"> 
    	<h1>Meet Myra!</h1>
	</div>
	<p>Learn more about who I am and my passions by navigating through these links:</p>
	<nav>
		<ul>
			<li style="margin-bottom: 10px;"><a href="#about-me">About Me</a></li>
			<li style="margin-bottom: 10px;"><a href="#my-family">My Family</a></li>
			<li style="margin-bottom: 10px;"><a href="#my-education">My Education</a></li>
		</ul>
	</nav>
</header>

<main>
	
	<section id="about-me">
		<h2>About Me</h2>
		<p>I am a dedicated and passionate individual who believes in working hard and achieving my goals. I have a strong interest in psychology and how it can be used to help people live better lives. I am also pursuing a degree in IT to 
			expand my skillset and be able to help others with technology. In addition to my passion for psychology and IT, I am also an advocate for personal growth and self-improvement. I firmly believe in the power of continuous learning 
			and strive to expand my knowledge and skills in various areas. I am always seeking new opportunities to challenge myself and embrace novel experiences that broaden my horizons.</p>
			
		<p>	Through my studies in psychology, I have developed a deep understanding of human behavior, cognition, and emotions. I am particularly fascinated by the ways in which individuals perceive the world and interact with others, 
			and I am driven by a genuine desire to help people navigate life's challenges and find fulfillment. I aspire to apply my psychological knowledge in a practical manner, whether through counseling, coaching, or developing 
			innovative interventions that promote mental well-being.</p>
			
		<p>	Simultaneously, my pursuit of a degree in IT has exposed me to the rapidly evolving world of technology. I am captivated by the potential of digital advancements to transform lives and improve society. With my expanding skillset, 
			I aim to bridge the gap between psychology and technology, exploring how these fields can collaborate to create innovative solutions for mental health, human interaction, and overall well-being. I am excited to combine my expertise 
			in psychology with my technical proficiency to develop user-friendly applications and digital platforms that empower individuals to lead healthier and more fulfilling lives.</p>
			
		<p>	Overall, my unwavering dedication, coupled with my passion for psychology and IT, fuels my drive to make a positive impact in people's lives. I am committed to utilizing my unique blend of knowledge and skills to contribute to the 
			well-being of individuals, the advancement of technology, and the betterment of society as a whole.</p>
	</section>

	<section id="my-family">
		<h2>My Family</h2>
		<p>My family is the cornerstone of my life, providing me with unwavering love, support, and strength. At the center of it all is my amazing husband, Tommy, whose steadfast presence and unwavering support have been instrumental in 
			my personal and professional journey. He is not only my rock but also my best friend, constantly encouraging me to pursue my passions and helping me overcome any obstacles that come my way.</p>
			
		<p>	Our two sons, Gabriel and Jeriah, bring immeasurable joy and laughter into our lives. They are a constant source of inspiration, reminding me of the beauty of innocence and the importance of cherishing every precious moment. With their 
			boundless energy and curiosity, they keep me on my toes and remind me to embrace the wonders of the world around us.</p>
			
		<p>	Together, as a family, we thrive on adventure and exploration. South Africa, with its diverse landscapes and rich cultural heritage, provides us with endless opportunities to create cherished memories. From breathtaking safaris to 
			captivating historical sites, we relish in immersing ourselves in the beauty and wonder of this remarkable country. Exploring together not only strengthens our bond but also allows us to appreciate the richness of the world we live in.</p>
	</section>

	<section id="my-education">
		<h2>My Education</h2>
		<p>I am currently pursuing a degree in IT and working towards becoming a skilled software developer. In addition, I have a Master's degree in Psychology and am a licensed psychologist, helping individuals and families work through their challenges.</p>
	</section>

	<nav>
		<p>Explore more of our website by navigating to the following pages:</p>
		<ul>
			<li style="margin-bottom: 10px;"><a href="{% url 'index' %}">Home</a></li>
			<li style="margin-bottom: 10px;"><a href="{% url 'blog_home' %}">Blog</a></li>
			<li style="margin-bottom: 10px;"><a href="{% url 'webapp:dashboard' %}">User Dashboard</a></li>
			<li style="margin-bottom: 10px;"><a href="{% url 'webapp:contact' %}">Contact Me</a></li> 
		</ul>
	</nav>
</main>

<footer>
	<p>&copy; 2023 Myra. All rights reserved.</p>
</footer>
</html>

webapp/templates/dashboard.html
<!DOCTYPE html>
<html>
<head>
	<title>dashboard</title>

    <style>
		.heading {
	text-align: center;
    	}
    </style>

</head>

<body>
	<header>
		<div class="welcome-message">
			<div class="heading">
                <h1>Myra's Psych-IT Hub</h1>
            </div>
            <h2>User Dashboard</h2>
			<p>Myra is a psychologist and IT student with a passion for blogging about her experiences. On this website, 
               she shares her insights, stories, and thoughts on various topics related to psychology and technology.</p>
		</div>
	
        <p>Get ready to explore the full potential of Myra's platform: </p>
		<nav>
			<ul>
				<li style="margin-bottom: 10px;"><a href="{% url 'index' %}">View the home page</a></li>
                <li style="margin-bottom: 10px;"><a href="{% url 'webapp:about_me' %}">Learn more about Myra</a></li>
                <li style="margin-bottom: 10px;"><a href="{% url 'blog_home' %}">Read Myra's blog</a></li>
				<li style="margin-bottom: 10px;"><a href="{% url 'webapp:contact' %}">How to Contact me</a></li>	
                <li style="margin-bottom: 10px;"><a href="{% url 'logout' %}">Logout</a></li>
			</ul>
		</nav>
    </header>
</body>

<footer>
	<p>&copy; 2023 Myra. All rights reserved.</p>
</footer>
</html>

webapp/templates/index.html
<!DOCTYPE html>
<html>
<head>
	<title>index</title> 
	<style>
		.heading {
	text-align: center;
    	}
    </style>	
</head>

<body>
	<header>
		<div class="heading">
			<h1>Myra's Psych-IT Hub</h1>
		</div>

		<p style="line-height: 1.5; margin-bottom: 20px;">Welcome to Myra's Psych-IT Hub, your gateway to the fascinating intersection of psychology and information technology!</p>

		<nav>
			<p>Explore more of our website by navigating to the following pages:</p>
			<ul>
				<li style="margin-bottom: 10px;"><a href="about_me">About Me</a></li>
				<li style="margin-bottom: 10px;"><a href="blog">Blog</a></li>
				<li style="margin-bottom: 10px;"><a href="dashboard">User Dashboard</a></li>
				<li style="margin-bottom: 10px;"><a href="contact">Contact Me</a></li>
				<li style="margin-bottom: 10px;"><a href="{% url 'login:login' %}">Login</a></li>
				<li style="margin-bottom: 10px;"><a href="{% url 'register:register' %}">Register Account</a></li>
			</ul>
		</nav>
	</header>

	<main>
		<h2>Hi, I'm Myra!</h2>
		<p style="line-height: 1.5; margin-bottom: 20px;">I am a hardworking woman living in South Africa. I am a wife to Tommy, mother of Gabriel and Jeriah, IT student, and psychologist.</p>
		<p style="line-height: 1.5; margin-bottom: 20px;"> As an IT student with a deep interest in psychology, Myra is dedicated to exploring the ways in which technology impacts 
			our mental well-being. Whether you're seeking insights into the psychological effects of social media, guidance on managing 
			digital distractions, or curious about the latest developments in online therapy platforms, Myra is here to provide you with 
			valuable perspectives.</p>

		<p style="line-height: 1.5; margin-bottom: 20px;">At Myra's Psych-IT Hub, we recognize the growing importance of understanding the psychological implications of technology. 
			With the rapid advancements in the digital realm, it is crucial to navigate the ever-evolving landscape mindfully. Myra combines 
			her passion for psychology with her IT expertise to offer you practical advice, research-backed strategies, and thought-provoking 
			content that sheds light on the relationship between psychology and technology.</p>
			
		<p style="line-height: 1.5; margin-bottom: 20px;">Embark on a journey of exploration as you dive into our collection of articles, blog posts, and resources that cover a wide range 
			of Psych-IT topics. Discover how technology can be harnessed to enhance well-being, productivity, and personal growth, while also 
			being aware of potential pitfalls. Join Myra, the IT student with a keen interest in psychology, and let's navigate the fascinating 
			realm of Psych-IT together!.</p>
	</main>
</body>

<footer>
	<p>&copy; 2023 Myra. All rights reserved.</p>
</footer>
</html>

webapp/templates/protected_page.html
<!DOCTYPE html>
<html>
<head>
    <title>Protected Page</title>
</head>
<body>
    <h1>Welcome to the protected page</h1>
    <p>This is a page that requires login to access.</p>

    <h2>About Me</h2>
    <p>This is the about me page content.</p>
    
    <h2>Dashboard</h2>
    <p>This is the dashboard page content.</p>
    
</body>
</html>

webapp/templates/webapp/contact.html
<!DOCTYPE html>
<html>
<head>
    <title>Contact</title>

    <style>
        form label,
        form input,
        form textarea {
    margin-bottom: 10px;
        } 

        textarea#message {
            height: 200px; 
            width: 300px;
            vertical-align: top;
        }

        input#name,
        input#email {
            width: 300px; 
        }

        input[type="submit"] {
            background-color: green;
            color: white;
            border: none;
            padding: 10px 20px;
            cursor: pointer;
        }

		.heading {
	text-align: center;
    	}
   
    </style>
</head>

<body>
    <header>
        <div class="heading"> 
            <h1>Contact Me</h1>
        </div>
    </header>

    <main>
        <section id="contact-me">
            <p>If you would like to get in touch with me, please fill out the form below, and I will get back to you as soon as possible.</p>
            <form action="#" method="post">
                <label for="name">Name:</label>
                <input type="text" id="name" name="name" required><br>

                <label for="email">Email:</label>
                <input type="email" id="email" name="email" required><br>

                <label for="message">Message:</label>
                <textarea id="message" name="message" required></textarea><br>

                <input type="submit" value="Submit">
            </form>
        </section>
        <nav>
            <p>Explore more of our website by navigating to the following pages:</p>
            <ul>
                <li style="margin-bottom: 10px;"><a href="{% url 'index' %}">Home</a></li>
                <li style="margin-bottom: 10px;"><a href="{% url 'webapp:about_me' %}">About Me</a></li>
				<li style="margin-bottom: 10px;"><a href="{% url 'blog_home' %}">Blog</a></li>
				<li style="margin-bottom: 10px;"><a href="{% url 'webapp:dashboard' %}">User Dashboard</a></li>
            </ul>
        </nav>
    </main>
</body>

<footer>
	<p>&copy; 2023 Myra. All rights reserved.</p>
</footer>
</html>
               